AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Parking Permit Renewal Lambda Function'

Resources:
  ParkingPermitFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: parking-permit-renewal
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: deployment_package.zip
      Timeout: 300
      MemorySize: 512
      Layers:
        - arn:aws:lambda:us-east-1:764866452798:layer:chrome-selenium:31
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: 'cron(0 12 * * ? *)'
            Name: parking-permit-daily-trigger
            Description: 'Daily trigger for parking permit renewal'
            Enabled: true
