AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Parking Permit Renewal Lambda Function'

Resources:
  SeleniumLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: selenium-chrome-layer
      ContentUri: selenium_layer.zip
      CompatibleRuntimes:
        - python3.9

  ParkingPermitFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: parking-permit-renewal
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: deployment_package.zip
      Timeout: 300
      MemorySize: 512
      Layers:
        - !Ref SeleniumLayer
      Policies:
        - AWSLambdaBasicExecutionRole

  DailyTriggerRule:
    Type: AWS::Events::Rule
    Properties:
      Name: parking-permit-daily-trigger
      ScheduleExpression: 'cron(0 12 * * ? *)'
      State: ENABLED
      Targets:
        - Arn: !GetAtt ParkingPermitFunction.Arn
          Id: ParkingPermitFunctionTarget
